#
# SPDX-License-Identifier: Apache-2.0
#

repository:
  name: cbom-catalog
  description: CBOM Catalog
  homepage: https://github.io/jonesn/cbom-catalog/latest/
  default_branch: main
  has_downloads: false
  has_issues: true
  has_projects: true
  has_wiki: true
  archived: false
  private: true
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
